### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by kshannon** [kshannon/intracranial-hemorrhage-detection#3]
- Please add an ```intracranial-hemorrhage-detection/eda/``` directory at the top level and put ```*.ipynb``` eda scrips in this folder.
- Tony, you had mentioned you did a first pass EDA on the data? If so you can upload it and maybe chris can do some more work on it once he gets the data?

**Comment by tonyreina** [comment]
My first pass was just to re-create a CSV with the filename and label vector.  I've also found several images while training that are either not 512x512 or have 0 standard deviation.  So there are some images in the dataset that seem to be blank??

**Comment by kshannon** [comment]
ok, good to know and yes I also have come across some that are either blank or corrupted? Maybe has to do with this training error:
```
ValueError: The length of the pixel data in the dataset (153710 bytes) doesn't match the expected length (524288 bytes). The dataset may be corrupted or there may be an issue with the pixel data handler.
```
We might just need to have a txt document to refer to when checking for "bad actors" might be better than plain deleting them?

**Comment by kshannon** [comment]
the error above:
```
ValueError: ("The length of the pixel data in the dataset (153710 bytes) doesn't match the expected length (524288 bytes). The dataset may be corrupted
or there may be an issue with the pixel data handler.", 'occurred at index 26401')
```
occurs in the validation set. The new csv: ```train_flagged.csv``` in the **src/** folder now has an added column BOOL for bad_actor where true = data is fine and false = data has wrong pixel size != (512, 512). I will need to rerun the ```bad_actors.py``` script from on the validation set and try to catch the ```ValueError``` for reading pixel data from the dicom which was added in 3b6f1035f44477c95d87d9cbded8f95a3ddbb61a

New training csv pushed in commit ab7611695821bb36c0052287e6b1bfac4f8ad4cf 
new validation script added in 49657106a011ecef30787e1bd97485b7d2b0fb9c
Added bad actors csv and master train/validate csvs to eda dir in c3e1e8d5cb39ec89e16718082f93bcc3a5f00ffa
created new train/validate csvs without bad data in src/ for use in pipeline 530c9fe89b8f855527f8ca35fda5253ca3fa91c2

The master csvs located in eda/ are the original files created by Tony's script withonly an added column for true/false, these will remain untouched as a single source of truth. The new train/validation CSVs in src/ are now candidate sources and will see if there is any error ocuurs during this next training run.

**Comment by kshannon** [comment]
@tonyreina @utcsox these commits and new csv files resolve the data issues we had, closing issue for now.
